### PR TITLE
fix deadlock when condition wait resumes and context is done

### PR DESCRIPTION
**Pull request by basvanbeek**
A deadlock can occur when `svc.cond.Wait` wakes up and finds context to be done. In the wake up, the mutex is locked. This same mutex is found in the defer block in the Run command and calls lock a second time.

### CODE REVIEW

**Comment by arkodg** [comment]
ptal @lestrrat

**Comment by lestrrat** [comment]
@arkodg @basvanbeek argh, I hate it when GitHub doesn't notify me... Looking into it

**Comment by lestrrat** [comment]
Thank you! I think the `Unlock()` makes sense, but removing that `<-ctx.Done()` I think actually exposes another problem in that the `drainPending()` goroutine is leaked. I think I'm going to run a few tests and create a separate PR that incorporates this

**Comment by lestrrat** [comment]
merged via #11

**Pull request closed without merging**
